### PR TITLE
Bugfixes, Moved method implementations from Ctxt.h to Ctxt.cpp

### LINKED ISSUE #275: Forward Declaration/Invalid use of incomplete type 'class FHEcontext'
simply including Ctxt.h results in following compilation error:

 In file included from src/common/test.h:11:0,
                 from src/common/test.cpp:8:
HElib/src/Ctxt.h: In member function ‘void Ctxt::addConstantCKKS(double)’:
HElib/src/Ctxt.h:385:69: error: invalid use of incomplete type ‘const class FHEcontext’
     addConstantCKKS(rationalApprox(x, /*denomBound=*/1<<getContext().alMod.getR()));
                                                                     ^
In file included from HElib/src/Ctxt.h:58:0,
                 from src/common/test.h:11,
                 from src/common/test.cpp:8:
HElib/src/DoubleCRT.h:23:7: note: forward declaration of ‘class FHEcontext’
 class FHEcontext;
       ^
In file included from src/common/test.h:11:0,
                 from src/common/test.cpp:8:
HElib/src/Ctxt.h: In member function ‘void Ctxt::multByP(long int)’:
HElib/src/Ctxt.h:450:39: error: invalid use of incomplete type ‘const class FHEcontext’
     long p2e = NTL::power_long(context.zMStar.getP(), e);

...AND MORE ERRORS OF THIS TYPE...

I think this happens because some methods are implemented in the header file and code calling methods from FHEcontext are processed before FHEcontext is defined. So in the Ctxt.h file we have only forward declarations, but use the type as if it is already defined. Solution would be to move implementations from Ctxt.h to the Ctxt.cpp file.

### PR DESCRIPTION
**Pull request by boev**
fixes #275

### CODE REVIEW

**Comment by boev** [comment]
Added small bug fixes:
1) FHEPubKey needs a virtual destructor (added default one). Why? Check this: https://stackoverflow.com/questions/827196/virtual-default-destructors-in-c

2) Fixed compare signed unsigned warning.

**Comment by boev** [comment]
Hmm as I understand it using long in the situation is not very safe. The change just makes a static cast for a safer comparison (compare size_t vs size_t, not long vs long) and does not change the logic. Actually when indexing gens[i] then i is automatically casted to size_t and for long this can cause a bit of extra time depending on how compiler optimizes it.  Using long will work most of the time and it is probably best to leave the old code and the warning so a more general fix is proposed in the future.

**Comment by shaih** [comment]
The problem with your code was the logic, not the cast. You did `(i<0) || something`, while it should have been `(i>=0) && something`.

Regarding the cast vs. lsize, this is a matter of style. The cast thing is much more verbose and harder to read, while indeed providing some extra protection (but against cases that never happen).

**Comment by boev** [comment]
You are 100% correct. Tests still works because probably the function is never called with negative values. The cast is one of many ways to make the code robuster, but in my opinion not the best one. So I will just leave it as it was.

**Pull request closed without merging**
