### PR TITLE
Enable Cmake build

### PR DESCRIPTION
**Pull request by fionser**
Basically, run `cmake .. & make` will finish all the build process.
1. We need to specify the path to NTL
2. To build test files, use `cmake -DENABLE_TEST=on`

### CODE REVIEW

**Comment by thEpisode** [comment]
Interesting proposal

**Comment by shaih** [comment]
Hi riku, can you modify your CMakeLists with the updated list of modules over the last few months?

Or even better, set some mechanism so that it is updated automatically based on whatever cpp files are found in the crs directory (I'm not familiar enough with cmake to know it if's easy to do in this case).

**Comment by fionser** [comment]
@shaih 
The Test_XX.cpp files are easy to filter out. However, some program files (MultTime.cpp, cgauss.cpp params.cpp eqtesting.cpp) should need some extra steps to filter out.

I am not sure whether a white list is suitable. Or we can place these files into a special directory.

**Comment by shaih** [comment]
@fionser 
I removed some of the redundant programs, and moved others to under 'misc'. I think that now all the main programs are of the form Test_XX.cpp

**Comment by fionser** [comment]
@shaih 
Thanks, and I adjusted the `src/CMakeLists.txt` for this.

**Pull request merged**
